#@KlopsruBot
TELEGRAM_BOT_TOKEN = ENV['TELEGRAM_BOT_TOKEN']
SECRET = ENV['SECRET']
TELEGRAM_SEND_MESSAGE_URL = "https://api.telegram.org/bot#{TELEGRAM_BOT_TOKEN}/sendMessage"
BOTAN_TOKEN = ENV['BOTAN_TOKEN']
